### ISSUE TITLE
Issues about copyModel function

### ISSUE THREAD

**Issue by xbq1994** [HeliosZhao/M3L#3]
Hi, why you write the copyModel function instead of using copy.deepcopy method?

**Comment by xbq1994** [comment]
Hi, I ran the code, but get mAP 10% and R1 28.3% on MSMT17_V2 with training on the market, duke and cuhk03

**Comment by HeliosZhao** [comment]
> Hi, why you write the copyModel function instead of using copy.deepcopy method?

This function is more like `load_state_dict` in PyTorch, and we follow [MWNet](https://github.com/xjtushujun/meta-weight-net) for this function.

**Comment by HeliosZhao** [comment]
> Hi, I ran the code, but get mAP 10% and R1 28.3% on MSMT17_V2 with training on the market, duke and cuhk03

Do you use 3 GPUs and the default hyperparameters? Which backbone do you use?

**Comment by xbq1994** [comment]
> > Hi, I ran the code, but get mAP 10% and R1 28.3% on MSMT17_V2 with training on the market, duke and cuhk03
> 
> Do you use 3 GPUs and the default hyperparameters? Which backbone do you use?

I use 1 GPU and the default hyperparameters. Should I use 3 GPUs instead?

**Comment by HeliosZhao** [comment]
Yes, ReID model is sensitive to the number of GPUs, probably due to BN. So the model cannot achieve satisfactory performance with only 1 GPU. 

Thank you for your interest. Please reproduce our results with 3 GPUs.

**Comment by xbq1994** [comment]
> Yes, ReID model is sensitive to the number of GPUs, probably due to BN. So the model cannot achieve satisfactory performance with only 1 GPU.
> 
> Thank you for your interest. Please reproduce our results with 3 GPUs.

Fine. Thanks a lot!
